REXX RXMQEVNT.REX WMQW SYSTEM.ADMIN.QMGR.EVENT    1>rxmqevnt.log 2>stderr
REXX RXMQEVNT.REX WMQW SYSTEM.ADMIN.CHANNEL.EVENT 1>>rxmqevnt.log 2>>stderr
REXX RXMQEVNT.REX WMQW SYSTEM.ADMIN.COMMAND.EVENT 1>>rxmqevnt.log 2>>stderr
REXX RXMQEVNT.REX WMQW SYSTEM.ADMIN.CONFIG.EVENT  1>>rxmqevnt.log 2>>stderr
REXX RXMQEVNT.REX WMQW SYSTEM.ADMIN.PERFM.EVENT   1>>rxmqevnt.log 2>>stderr
